# Generated by Django 3.2.5 on 2023-07-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=25)),
                ('fee', models.IntegerField()),
                ('due', models.IntegerField()),
                ('dur', models.IntegerField()),
                ('trainer', models.CharField(max_length=25)),
            ],
        ),
    ]
