# Generated by Django 3.2.5 on 2023-07-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='due',
        ),
    ]
